#!/bin/sh
# Copyright © 2026 & onwards, Alessandro Di Ronza <ales.drnz@gmail.com>.
# All rights reserved.
# Use of this source code is governed by BSD 3-Clause license that can be found in the LICENSE file.
#
# Regenerates layer/src/hdr_shaders.h from layer/shaders/*.
#
# The generated header is checked in, so building the project needs no shader
# compiler; this script needs glslangValidator and is run by whoever edits a
# shader, with the result reviewed and committed like any other source change.
set -eu

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/layer/src/hdr_shaders.h"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

emit() {
    name="$1"
    file="$2"
    printf 'static const uint32_t %s[] = {\n' "$name"
    # 4-byte words, little-endian, as VkShaderModuleCreateInfo wants them.
    od -A n -t x4 -v "$file" | sed 's/^ *//; s/ \+/ /g; s/ $//; s/\([0-9a-f]\{8\}\)/0x\1u,/g'
    printf '};\n'
}

glslangValidator -V "$root/layer/shaders/overlay.vert" -o "$tmp/overlay.vert.spv" >/dev/null
glslangValidator -V "$root/layer/shaders/hdr.frag" -o "$tmp/hdr.frag.spv" >/dev/null

{
    printf '// Generated by scripts/compile-shaders.sh from layer/shaders/ -- do not edit.\n'
    printf '// Copyright © 2026 & onwards, Alessandro Di Ronza <ales.drnz@gmail.com>.\n'
    printf '// All rights reserved.\n'
    printf '// Use of this source code is governed by BSD 3-Clause license that can be found in the LICENSE file.\n'
    printf '#ifndef VOCEM_HDR_SHADERS_H\n#define VOCEM_HDR_SHADERS_H\n\n'
    printf '#include <cstdint>\n\n'
    emit vocem_overlay_vert_spv "$tmp/overlay.vert.spv"
    printf '\n'
    emit vocem_hdr_frag_spv "$tmp/hdr.frag.spv"
    printf '\n#endif  // VOCEM_HDR_SHADERS_H\n'
} > "$out"

echo "wrote $out"
