// Copyright © 2026 & onwards, Alessandro Di Ronza <ales.drnz@gmail.com>.
// All rights reserved.
// Use of this source code is governed by BSD 3-Clause license that can be found in the LICENSE file.

#include "vocem/fonts.h"

#include <cmath>
#include <cstring>
#include <initializer_list>

#include "vocem/emoji_bank.h"
#include "vocem/shared_state.h"

namespace vocem {
namespace {

// Generated by scripts/make-fonts.py from third_party/fonts. Two weights of Inter
// for the letters and every symbol it carries, Noto Emoji for the emoji, and a
// slice of Noto Sans JP for the punctuation a channel name is written with and
// Inter has none of.
#include "inter_regular.inc"
#include "inter_semibold.inc"
#include "noto_emoji.inc"
#include "noto_punctuation.inc"

// The size the panel's spacing constants were tuned against, and the default of
// the font_size setting. Everything in panel.cpp is a multiple of ui_scale().
constexpr float kReferenceSize = 16.0f;

// A 1080p output gets 16-pixel text, which is about what the Discord client uses,
// and larger outputs get proportionally more.
constexpr float kReferenceHeight = 1080.0f;

Fonts g_fonts;

// The same sets the three TTFs were subset to. Asking ImGui for ranges a font does
// not contain costs nothing, but asking for less than it contains would silently
// drop characters -- which is what happened to every symbol between the quotes and
// the arrows, and to every emoji, for as long as this list was four lines long.
const ImWchar* letter_ranges() {
    static const ImWchar ranges[] = {
        0x0020, 0x00FF,  // Basic Latin, Latin-1 Supplement
        0x0100, 0x024F,  // Latin Extended-A and B
        0x0370, 0x03FF,  // Greek
        0x0400, 0x04FF,  // Cyrillic
        // Punctuation, currency, letterlike forms, arrows, mathematics, box
        // drawing, geometric shapes, dingbats: everything Inter draws above the
        // scripts. Stars, ticks, bullets and card suits all live in here.
        0x2000, 0x2BFF,
        0,
    };
    return ranges;
}

const ImWchar* emoji_ranges() {
    static const ImWchar ranges[] = {
        // The two variation selectors and the zero-width joiner, which Noto Emoji
        // maps to blanks -- without them every emoji that carries one would be
        // followed by a question mark, since a code point no font in the atlas has
        // is drawn as one.
        0x200D, 0x200D,
        0xFE0E, 0xFE0F,
        // Not everything that is an emoji lives above U+1F000. ⭐ is U+2B50 and ✅
        // is U+2705, both down among the symbols, and both were still question
        // marks when this range started at U+1F000 -- which is what a game showed.
        //
        // The overlap with Inter is deliberate and free: ImGui's merge keeps the
        // glyph that is already there, so Inter's star, tick, heart and digits
        // stay Inter's and only what it does not have is filled in from here.
        0x2190, 0x2BFF,
        0x3030, 0x303D,
        0x3297, 0x3299,
        0x1F000, 0x1FAFF,
        0,
    };
    return ranges;
}

const ImWchar* punctuation_ranges() {
    static const ImWchar ranges[] = {
        0x3000, 0x303F,  // CJK punctuation: the brackets and stops
        0x30FB, 0x30FC,  // the katakana middle dot, which Discord names are full of
        0xFF01, 0xFF60,  // fullwidth forms
        0,
    };
    return ranges;
}

// Emoji are rasterised at this size at most, however large the text is. Every
// glyph in the atlas costs its area, and 1500 emoji at 64 pixels is eight
// megabytes of texture in somebody's game -- measured, not guessed. Above this
// they are drawn a little smaller than the text around them, which is what a
// typeface does with them anyway.
constexpr float kEmojiCeiling = 32.0f;

// The ceiling is also the size of the buffer the bank's pixels are resampled
// into, and `emoji_bank_resample` writes size*size*4 bytes -- so a ceiling above
// the bank's own size would overflow a stack buffer inside somebody's game, and
// would ask the resample to scale *up*, which its own comment says it never
// does. One constant away from a crash is close enough to say so in the
// compiler.
static_assert(kEmojiCeiling <= static_cast<float>(kEmojiBankPixels),
              "the emoji ceiling may not exceed the bank's own pixel size");

// Every codepoint the session's text has shown us, in codepoint order, with
// bit 31 carrying "the bank has it". The rejected ones are remembered too, on
// purpose: a name with a typographic apostrophe shows the same codepoint every
// frame, and forgetting the rejection would put a bank lookup -- file reads --
// on the per-frame path. A fixed array, because everything here can run inside
// a game; past the cap new emoji stay monochrome, which still draws.
constexpr uint32_t kMaxSeenCodepoints = 96;
constexpr uint32_t kSeenInBank = 0x80000000u;
uint32_t g_seen[kMaxSeenCodepoints];
uint32_t g_seen_count = 0;
// How many bank emoji are wanted, and how many the current atlas carries;
// fewer built than wanted means the next ensure_fonts() rebuilds.
uint32_t g_wanted_count = 0;
uint32_t g_built_count = 0;
EmojiBank g_emoji_bank;
// Set when a codepoint arrived with the table already full: past the cap a new
// colour emoji stays monochrome for the session, which is a decision worth
// saying out loud rather than a silence.
bool g_capped = false;

void note_emoji_codepoint(uint32_t codepoint) {
    // Below the symbols there are no emoji, and Inter's own glyphs win anyway.
    if (codepoint < 0x2000 || codepoint > 0x10FFFF) {
        return;
    }
    long low = 0;
    long high = static_cast<long>(g_seen_count) - 1;
    while (low <= high) {
        const long middle = low + (high - low) / 2;
        const uint32_t entry = g_seen[middle] & ~kSeenInBank;
        if (entry == codepoint) {
            return;  // seen before, verdict remembered either way
        }
        if (entry < codepoint) {
            low = middle + 1;
        } else {
            high = middle - 1;
        }
    }
    if (g_seen_count >= kMaxSeenCodepoints) {
        g_capped = true;
        return;
    }
    // The one bank lookup this codepoint will ever cost.
    const bool in_bank = g_emoji_bank.contains(codepoint);
    std::memmove(&g_seen[low + 1], &g_seen[low],
                 (g_seen_count - static_cast<uint32_t>(low)) * sizeof(uint32_t));
    g_seen[low] = codepoint | (in_bank ? kSeenInBank : 0);
    ++g_seen_count;
    if (in_bank) {
        ++g_wanted_count;
    }
}

}  // namespace

void fonts_note_emoji(const char* utf8_text) {
    if (!utf8_text || !utf8_text[0]) {
        return;
    }
    utf8_each(utf8_text, [](uint32_t codepoint) { note_emoji_codepoint(codepoint); });
}

void fonts_note_emoji_in(const Snapshot& snapshot) {
    fonts_note_emoji(snapshot.channel_name);
    for (uint32_t i = 0; i < snapshot.user_count && i < kMaxUsers; ++i) {
        fonts_note_emoji(snapshot.users[i].name);
    }
    fonts_note_emoji(snapshot.notification.title);
    fonts_note_emoji(snapshot.notification.body);
}

const char* fonts_emoji_status() {
    // The bank's own refusal first: it is the one that means "none at all".
    if (const char* reason = g_emoji_bank.reason()) {
        return reason;
    }
    if (g_capped) {
        return "the colour emoji table is full: further emoji stay monochrome";
    }
    return nullptr;
}

const Fonts& fonts() { return g_fonts; }

float font_pixel_size(uint32_t height, float user_scale, float reference) {
    // Whole pixels. The size is what every distance in the panel is a multiple of,
    // and ImGui truncates the content extent it fits a window to: with a fractional
    // line height the accumulated fraction came off the bottom padding and the last
    // avatar in the list was clipped by the box's own edge. It is also the size the
    // glyphs are rasterised at, and a whole number is the crisper of the two.
    const float proportional = std::round(
        reference * (static_cast<float>(height) / kReferenceHeight) * user_scale);
    // Below about 11 pixels an interface font stops being readable at all, and
    // above 64 the atlas grows faster than the value of the extra detail.
    if (proportional < 11.0f) {
        return 11.0f;
    }
    if (proportional > 64.0f) {
        return 64.0f;
    }
    return proportional;
}

float ui_scale() {
    const float reference = g_fonts.reference > 0.0f ? g_fonts.reference : kReferenceSize;
    return g_fonts.pixel_size > 0.0f ? g_fonts.pixel_size / reference : 1.0f;
}

bool ensure_fonts(float pixel_size, float reference) {
    // The reference is not a size the atlas is built at -- it is what the layout
    // divides by -- so it costs nothing to follow immediately.
    g_fonts.reference = reference > 0.0f ? reference : kReferenceSize;

    ImFontAtlas* atlas = ImGui::GetIO().Fonts;

    // Half a pixel of difference is not worth throwing an atlas away for -- and
    // without a dead band, a size derived from a continuous slider would rebuild
    // on every frame the user is dragging it.
    //
    // The dead band holds only while the atlas it remembers building is still the
    // one in front of us. Both injected paths destroy their ImGui context and
    // create another in the same process -- the GL overlay when the user switches
    // it off and back on, the Vulkan layer when a game replaces its device -- and
    // the fresh context brings a fresh, empty atlas at the same pixel size. A
    // size-only dead band answered "nothing to do" and left the pointers below
    // aimed into the atlas that died with the old context; the first PushFont of
    // the first frame after the overlay came back crashed the game. An atlas this
    // module has filled is never empty, so empty means: not ours yet, build.
    if (g_fonts.pixel_size > 0.0f && atlas->Fonts.Size > 0 &&
        pixel_size > g_fonts.pixel_size - 0.5f && pixel_size < g_fonts.pixel_size + 0.5f &&
        g_built_count == g_wanted_count) {
        return false;
    }

    atlas->Clear();

    ImFontConfig config;
    config.FontDataOwnedByAtlas = false;  // the data is static, not heap
    // Inter's outlines are drawn for interfaces; the light hinting ImGui applies by
    // default is right for it. Oversampling stays at ImGui's default of 2 in the
    // horizontal direction, which is what makes small text look clean.

    // A merged glyph belongs to the font it was merged into, so each weight gets
    // its own copy of the emoji and the punctuation: the channel name is drawn in
    // the heavier one, and it is exactly where an emoji turns up.
    const float emoji_size = pixel_size < kEmojiCeiling ? pixel_size : kEmojiCeiling;
    auto add_weight = [&](const unsigned char* data, unsigned int size) {
        ImFont* font = atlas->AddFontFromMemoryCompressedTTF(
            data, static_cast<int>(size), pixel_size, &config, letter_ranges());

        ImFontConfig merge = config;
        merge.MergeMode = true;
        atlas->AddFontFromMemoryCompressedTTF(
            NotoPunctuation_compressed_data,
            static_cast<int>(NotoPunctuation_compressed_size), pixel_size, &merge,
            punctuation_ranges());
        atlas->AddFontFromMemoryCompressedTTF(
            NotoEmoji_compressed_data, static_cast<int>(NotoEmoji_compressed_size),
            emoji_size, &merge, emoji_ranges());
        return font;
    };

    g_fonts.body = add_weight(InterRegular_compressed_data, InterRegular_compressed_size);
    g_fonts.strong = add_weight(InterSemiBold_compressed_data, InterSemiBold_compressed_size);

    // A failure here would leave the atlas empty and ImGui would assert on the
    // first frame, so fall back to the built-in bitmap rather than draw nothing.
    if (!g_fonts.body) {
        atlas->AddFontDefault();
        g_fonts.body = atlas->Fonts.empty() ? nullptr : atlas->Fonts[0];
        g_fonts.strong = g_fonts.body;
    }
    if (!g_fonts.strong) {
        g_fonts.strong = g_fonts.body;
    }

    // The colour emoji the session has seen, as coloured glyphs. Each weight
    // gets its own rect (a merged glyph belongs to the font it was merged into
    // -- the same lesson the monochrome emoji taught), reserved before Build
    // and filled with the bank's pixels after, resampled to the emoji size the
    // atlas is using. Straight alpha, which is what the atlas holds for every
    // other glyph. The monochrome font stays merged underneath: a codepoint
    // past the seen-cap, or a session with no bank on disk, draws exactly as
    // it did before this existed.
    const int emoji_px = static_cast<int>(emoji_size);
    const float emoji_offset_y = std::round((pixel_size - emoji_size) * 0.5f);
    // One rect per weight per bank emoji. The arrays are exactly full at the
    // cap, with no margin at all -- so the number of weights is named, the size
    // follows it, and a third weight fails to compile instead of writing past
    // two stack arrays inside a game.
    constexpr uint32_t kAtlasWeights = 2;
    constexpr uint32_t kMaxRects = kMaxSeenCodepoints * kAtlasWeights;
    int rect_index[kMaxRects];
    uint32_t rect_codepoint[kMaxRects];
    uint32_t rect_count = 0;
    if (g_fonts.body && g_fonts.strong && g_fonts.body != g_fonts.strong) {
        for (uint32_t i = 0; i < g_seen_count; ++i) {
            if (!(g_seen[i] & kSeenInBank)) {
                continue;
            }
            if (rect_count + kAtlasWeights > kMaxRects) {
                break;
            }
            const uint32_t codepoint = g_seen[i] & ~kSeenInBank;
            for (ImFont* font : {g_fonts.body, g_fonts.strong}) {
                static_assert(kAtlasWeights == 2, "one rect per weight, and there are two");
                const int index = atlas->AddCustomRectFontGlyph(
                    font, static_cast<ImWchar>(codepoint), emoji_px, emoji_px,
                    static_cast<float>(emoji_px + 1), ImVec2(0.0f, emoji_offset_y));
                atlas->CustomRects[index].GlyphColored = 1;
                rect_index[rect_count] = index;
                rect_codepoint[rect_count] = codepoint;
                ++rect_count;
            }
        }
    }

    atlas->Build();

    if (rect_count > 0) {
        unsigned char* pixels = nullptr;
        int atlas_width = 0;
        int atlas_height = 0;
        atlas->GetTexDataAsRGBA32(&pixels, &atlas_width, &atlas_height);
        unsigned char record[kEmojiBankRgbaBytes];
        unsigned char scaled[kEmojiBankRgbaBytes];
        for (uint32_t i = 0; i < rect_count; ++i) {
            const ImFontAtlasCustomRect* rect = atlas->GetCustomRectByIndex(rect_index[i]);
            if (!pixels || !rect->IsPacked() ||
                !g_emoji_bank.load(rect_codepoint[i], record)) {
                continue;
            }
            emoji_bank_resample(record, scaled, static_cast<uint32_t>(rect->Width));
            for (int row = 0; row < rect->Height; ++row) {
                std::memcpy(pixels + ((rect->Y + row) * atlas_width + rect->X) * 4,
                            scaled + row * rect->Width * 4,
                            static_cast<size_t>(rect->Width) * 4);
            }
        }
    }

    g_built_count = g_wanted_count;
    g_fonts.pixel_size = pixel_size;
    return true;
}

}  // namespace vocem
