// Copyright © 2026 & onwards, Alessandro Di Ronza <ales.drnz@gmail.com>.
// All rights reserved.
// Use of this source code is governed by BSD 3-Clause license that can be found in the LICENSE file.

#include "vocem/fonts.h"
#ifndef VOCEM_IMCONFIG_INJECTED
#error "vocem/imconfig_injected.h is not in effect: IM_ASSERT would be assert() inside a game"
#endif

#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>

#include <atomic>
#include <cmath>
#include <cstring>
#include <initializer_list>

#include "vocem/emoji_bank.h"
#include "vocem/shared_state.h"

namespace vocem {
namespace {

// Generated by scripts/make-fonts.py from third_party/fonts. Two weights of Inter
// for the letters and every symbol it carries, Noto Emoji for the emoji, and a
// slice of Noto Sans JP for the punctuation a channel name is written with and
// Inter has none of.
#include "inter_regular.inc"
#include "inter_semibold.inc"
#include "noto_emoji.inc"
#include "noto_math.inc"
#include "noto_punctuation.inc"
#include "noto_symbols.inc"
#include "noto_symbols2.inc"

// The size the panel's spacing constants were tuned against, and the default of
// the font_size setting. Everything in panel.cpp is a multiple of ui_scale().
constexpr float kReferenceSize = 16.0f;

// A 1080p output gets 16-pixel text, which is about what the Discord client uses,
// and larger outputs get proportionally more.
constexpr float kReferenceHeight = 1080.0f;

Fonts g_fonts;

// The same sets the three TTFs were subset to. Asking ImGui for ranges a font does
// not contain costs nothing, but asking for less than it contains would silently
// drop characters -- which is what happened to every symbol between the quotes and
// the arrows, and to every emoji, for as long as this list was four lines long.
const ImWchar* letter_ranges() {
    static const ImWchar ranges[] = {
        0x0020, 0x00FF,  // Basic Latin, Latin-1 Supplement
        0x0100, 0x024F,  // Latin Extended-A and B
        0x0250, 0x02FF,  // IPA and the modifier letters (superscript alphabets)
        0x0370, 0x03FF,  // Greek
        0x0400, 0x04FF,  // Cyrillic
        0x1D00, 0x1DBF,  // phonetic extensions, more of the fancy-name letters
        0x1F00, 0x1FFF,  // Greek Extended
        // Punctuation, currency, letterlike forms, arrows, mathematics, box
        // drawing, geometric shapes, dingbats: everything Inter draws above the
        // scripts. Stars, ticks, bullets and card suits all live in here.
        0x2000, 0x2BFF,
        0,
    };
    return ranges;
}

// The three symbol fonts (Noto Sans Math, Symbols, Symbols 2), which exist
// because Discord servers decorate channel and display names from
// symbol-picker sites: box fragments, circled letters, the arrows Inter does
// not carry, and the mathematical alphanumerics the "fancy font" alphabets
// really are. Merged after Inter -- the merge keeps the glyph already there --
// and rasterised at the emoji ceiling, for the emoji's own reason: ~2000
// decorations at 64 px is atlas nobody can afford, and a decoration drawn at
// 32 px in larger text is the trade the emoji already made.
const ImWchar* symbol_ranges() {
    static const ImWchar ranges[] = {
        0x0660, 0x0669,    // Arabic-Indic digits, which shape alone
        0x06F0, 0x06F9,    // and their Eastern forms
        0x2100, 0x2BFF,    // letterlike through misc symbols and arrows
        0x1D400, 0x1D7FF,  // mathematical alphanumerics
        0,
    };
    return ranges;
}

const ImWchar* emoji_ranges() {
    static const ImWchar ranges[] = {
        // The two variation selectors and the zero-width joiner, which Noto Emoji
        // maps to blanks -- without them every emoji that carries one would be
        // followed by a question mark, since a code point no font in the atlas has
        // is drawn as one.
        0x200D, 0x200D,
        0xFE0E, 0xFE0F,
        // Not everything that is an emoji lives above U+1F000. ⭐ is U+2B50 and ✅
        // is U+2705, both down among the symbols, and both were still question
        // marks when this range started at U+1F000 -- which is what a game showed.
        //
        // The overlap with Inter is deliberate and free: ImGui's merge keeps the
        // glyph that is already there, so Inter's star, tick, heart and digits
        // stay Inter's and only what it does not have is filled in from here.
        0x2190, 0x2BFF,
        0x3030, 0x303D,
        0x3297, 0x3299,
        0x1F000, 0x1FAFF,
        0,
    };
    return ranges;
}

const ImWchar* punctuation_ranges() {
    static const ImWchar ranges[] = {
        0x2500, 0x259F,  // box drawing and block elements, complete in this font
        0x3000, 0x303F,  // CJK punctuation: the brackets and stops
        0x3041, 0x30FF,  // the kana, which decorated names borrow whole
        0x3131, 0x318E,  // Hangul compatibility jamo, same use
        0x3200, 0x33FF,  // enclosed and compatibility CJK: circled forms, units
        0xFE30, 0xFE6F,  // vertical/compat forms and the small form variants
        0xFF01, 0xFF60,  // fullwidth forms
        0,
    };
    return ranges;
}

// Emoji are rasterised at this size at most, however large the text is. Every
// glyph in the atlas costs its area, and 1500 emoji at 64 pixels is eight
// megabytes of texture in somebody's game -- measured, not guessed. Above this
// they are drawn a little smaller than the text around them, which is what a
// typeface does with them anyway.
constexpr float kEmojiCeiling = 32.0f;

// The symbol fonts' own ceiling, lower than the emoji's: they carry about
// 2400 glyphs between them (the mathematical alphanumerics alone are 1024),
// and at the emoji's 32 px the whole atlas doubled at 4K -- measured,
// 2048x4096 to 4096x4096, 64 MB of RGBA in somebody's game. At 24 px it
// stays within the pre-symbol footprint's next step. A name decoration drawn
// at 24 px inside larger text is the same trade the emoji made at 32.
constexpr float kSymbolCeiling = 24.0f;

// The ceiling is also the size of the buffer the bank's pixels are resampled
// into, and `emoji_bank_resample` writes size*size*4 bytes -- so a ceiling above
// the bank's own size would overflow a stack buffer inside somebody's game, and
// would ask the resample to scale *up*, which its own comment says it never
// does. One constant away from a crash is close enough to say so in the
// compiler.
static_assert(kEmojiCeiling <= static_cast<float>(kEmojiBankPixels),
              "the emoji ceiling may not exceed the bank's own pixel size");

// Every codepoint the session's text has shown us, in codepoint order, with
// bit 31 carrying "the bank has it". The rejected ones are remembered too, on
// purpose: a name with a typographic apostrophe shows the same codepoint every
// frame, and forgetting the rejection would put a bank lookup -- file reads --
// on the per-frame path. A fixed array, because everything here can run inside
// a game.
//
// **Two budgets, because they are two different things.** This array is the
// remembered verdict, and its size is only about not asking the bank twice; the
// atlas budget below is about how many coloured rectangles a rebuild can carry.
// They were one number, ninety-six, and the array counted every codepoint from
// U+2000 up whether the bank had it or not -- so a channel of decorated and CJK
// names filled it with characters that were never going to be coloured, and
// from then on every emoji that arrived stayed monochrome for the life of the
// process. Measured: ninety-eight ideographs seen in names, then
// `fonts_emoji_status()` reporting the table full and a fire arriving
// afterwards drawn by the monochrome font. Which reads, from a chair, as
// "sometimes they are coloured and sometimes they are not".
constexpr uint32_t kMaxSeenCodepoints = 512;
// How many bank glyphs one atlas carries. This is the number with a cost behind
// it: one custom rectangle per weight per emoji, each the emoji's own square of
// texture (kEmojiCeiling above says what that is worth).
constexpr uint32_t kMaxBankGlyphs = 96;
constexpr uint32_t kSeenInBank = 0x80000000u;
// Whether this codepoint's pixels are already in the atlas. A codepoint is at
// most U+10FFFF, so the two flags and the value share a word without arithmetic.
constexpr uint32_t kSeenFolded = 0x40000000u;
// Whether the fold actually PLACED its glyph -- in at least one weight, which
// in practice is both. kSeenFolded is set before the work, so a bank read that
// failed or a rect that did not pack is settled too; this one says a glyph
// exists, which is what a text rewritten into the codepoint needs.
constexpr uint32_t kSeenPlaced = 0x20000000u;
constexpr uint32_t kCodepointMask = 0x00FFFFFFu;
static_assert(kCodepointMask >= 0x10FFFFu, "every Unicode codepoint fits below the flags");
uint32_t g_seen[kMaxSeenCodepoints];
uint32_t g_seen_count = 0;
// How many bank emoji are wanted, and how many the current atlas carries;
// fewer built than wanted means the next ensure_fonts() folds the difference in.
uint32_t g_wanted_count = 0;
uint32_t g_built_count = 0;

// One rect per weight per bank emoji, ALL of them reserved by every build
// whether or not an emoji has been seen yet -- which is what lets a new one be
// folded into the atlas in place instead of rasterising the whole atlas again.
// The number of weights is named and the sizes follow it, so a third weight
// fails to compile instead of writing past an array inside a game.
constexpr uint32_t kAtlasWeights = 2;
constexpr uint32_t kMaxRects = kMaxBankGlyphs * kAtlasWeights;
static_assert(kAtlasWeights == 2, "one rect per weight, and there are two");
// The reserved rectangles of the CURRENT atlas, in build order: slot i holds
// the two rects of the (i)th emoji to be folded. -1 until a build fills them.
int g_emoji_rects[kMaxRects];
// The vertical offset the emoji glyphs are placed at, which follows the atlas's
// pixel size and is therefore the build's, not the fold's.
float g_emoji_offset_y = 0.0f;
// How many slots the current atlas has handed out, and whether the reservation
// happened at all (it does not when the two weights are the same font).
uint32_t g_emoji_slots = 0;
bool g_emoji_reserved = false;
// The rectangles folded since a caller last asked (fonts_take_folded). At most
// every reserved rect of one atlas, so the array cannot overflow.
static_assert(kMaxFoldedRegions == kMaxRects, "fonts.h promises the caller's capacity");
static_assert(static_cast<float>(kMaxFoldedSide) >= kEmojiCeiling,
              "a folded square is an emoji square, at most the ceiling on a side");
AtlasRegion g_folded[kMaxRects];
uint32_t g_folded_count = 0;
// Every run of the rasteriser, counted (fonts.h says why a count and not a
// clock). Both of build_atlas()'s calls are in it, including the second one a
// refused typeface forces: that IS a rasterisation, and a count that hid it
// would be measuring what it wished for.
uint32_t g_build_count = 0;
// Set once fonts_atlas() has made the atlas object (fonts_atlas_made()).
std::atomic<bool> g_atlas_made{false};
EmojiBank g_emoji_bank;
// Set when a codepoint arrived with the table already full: past the cap a new
// colour emoji stays monochrome for the session, which is a decision worth
// saying out loud rather than a silence.
bool g_capped = false;

// The typeface the atlas was last built from, so a change of family rebuilds it
// the way a change of size does. Fixed arrays: this is compared inside a game,
// and a path longer than this is a path the window did not write.
constexpr size_t kMaxFontPath = 512;
// What the caller last ASKED for, which is what the dead band compares against,
// and what the last build actually USED, which is empty whenever the chosen face
// was refused. They were one pair of arrays, and the difference is a frame's
// whole budget: a face that gets past looks_like_a_font() and still cannot be
// rasterised makes ensure_fonts() forget the paths, so on the next call the
// remembered path no longer matched the settings' and every frame rebuilt the
// atlas from scratch -- measured at 61 ms per call on this machine, once per
// frame, in somebody's game, with a font-texture upload behind it (and a
// vkQueueWaitIdle behind that on the Vulkan side).
char g_asked_body[kMaxFontPath] = {};
char g_asked_strong[kMaxFontPath] = {};
char g_body_path[kMaxFontPath] = {};
char g_strong_path[kMaxFontPath] = {};
const char* g_font_reason = nullptr;

// A font a game may be handed. The rules are the ones every other read in this
// project follows (entries 47, 82, 86): a regular file, opened once, capped, and
// refused out loud rather than half-read.
//
// A cap, because ImGui's own AddFontFromFileTTF has none and the path comes out
// of a text file: a "font" of three hundred megabytes would be read whole into
// somebody's game. Sixteen is past every real face -- Noto Sans CJK, the
// largest thing a desktop is likely to carry, is under nine.
//
// Deliberately not O_NOFOLLOW, unlike the daemon's reads of a sandbox's
// directory: a font under /usr/share/fonts is very often reached through a
// symlink, and this path was written by the user's own settings window rather
// than by an untrusted peer. What is guarded here is size and kind.
constexpr size_t kMaxFontBytes = 16u * 1024u * 1024u;

void* read_font_file(const char* path, size_t* size_out) {
    *size_out = 0;
    const int fd = open(path, O_RDONLY | O_CLOEXEC);
    if (fd < 0) {
        g_font_reason = "the chosen font could not be opened";
        return nullptr;
    }
    struct stat info {};
    if (fstat(fd, &info) != 0 || !S_ISREG(info.st_mode)) {
        close(fd);
        g_font_reason = "the chosen font is not a regular file";
        return nullptr;
    }
    if (info.st_size <= 0 || static_cast<size_t>(info.st_size) > kMaxFontBytes) {
        close(fd);
        g_font_reason = "the chosen font is empty or larger than a font should be";
        return nullptr;
    }
    const size_t size = static_cast<size_t>(info.st_size);
    void* data = IM_ALLOC(size);
    if (!data) {
        close(fd);
        g_font_reason = "there was no room to read the chosen font";
        return nullptr;
    }
    size_t got = 0;
    while (got < size) {
        const ssize_t chunk = read(fd, static_cast<char*>(data) + got, size - got);
        if (chunk <= 0) {
            break;
        }
        got += static_cast<size_t>(chunk);
    }
    close(fd);
    if (got != size) {
        IM_FREE(data);
        g_font_reason = "the chosen font could not be read to the end";
        return nullptr;
    }
    *size_out = size;
    return data;
}

// Whether those bytes are a font at all, asked before the rasteriser is handed
// them.
//
// stb_truetype trusts its input. Given a file that is not a font,
// stbtt_GetFontOffsetForIndex returns -1, ImGui's IM_ASSERT on that is compiled
// out of every release build (this project's are RelWithDebInfo, so NDEBUG), and
// stbtt_InitFont then parses from `data - 1` with a table count read out of
// whatever happened to be there: measured as a SIGSEGV inside ensure_fonts,
// which is to say inside somebody's game, at imstb_truetype.h:1313 with
// fontstart 4294967295. A path is a line in a text file, so this is reachable
// from a hand-edited settings file, from a font uninstalled and its name reused,
// and from anything that writes the key without asking fontconfig.
//
// The signatures are the ones stbtt__isfont accepts (imstb_truetype.h:1299),
// plus the collection tag stbtt_GetFontOffsetForIndex follows -- so nothing this
// accepts is refused later for its header. The extra question is the one stb
// does not ask: that the table directory the count describes is inside the file
// that was actually read. Everything past that is the rasteriser's job, and its
// answer is Build()'s return value.
bool looks_like_a_font(const unsigned char* data, size_t size) {
    // Every bound is written as a subtraction from the size rather than as an
    // addition to an offset: the offset comes out of the file, and at 32 bits
    // `offset + 4` on a value near the top of the range wraps to something
    // small and passes the check it was supposed to fail. Both widths run this.
    const auto tag_at = [data, size](size_t offset, const unsigned char (&wanted)[4]) {
        return offset <= size && size - offset >= 4 &&
               std::memcmp(data + offset, wanted, 4) == 0;
    };
    const auto be32 = [data](size_t offset) {
        return (static_cast<uint32_t>(data[offset]) << 24) |
               (static_cast<uint32_t>(data[offset + 1]) << 16) |
               (static_cast<uint32_t>(data[offset + 2]) << 8) |
               static_cast<uint32_t>(data[offset + 3]);
    };
    // An offset table: the tag, then a count of tables, then that many 16-byte
    // records, each naming a table's offset and length. Anything shorter than
    // the directory it claims is truncated, and so is anything whose tables
    // reach past the bytes that were actually read.
    //
    // The second question is the one a truncated file fails, and it had to be
    // asked: stb_truetype does no bounds checking of its own, so a real font
    // cut short -- an interrupted copy, a file still being written, a partly
    // synced home directory -- passed the header check and then read past the
    // end of the buffer. Measured against the code that shipped 0.1.3, at four
    // truncation lengths of one installed DejaVu (400, 1024, 4096 and 65536
    // bytes): SIGSEGV every time, inside ensure_fonts, which is inside
    // somebody's game.
    //
    // What this bounds is a font that was cut off, not a font that was built to
    // do harm: with every table inside the file, stb can still be sent past the
    // end by a `loca` entry that lies about where a glyph is. That is worth
    // saying plainly rather than implying otherwise -- the threat model here is
    // accident, because this path is named by the user's own settings file and
    // not by an untrusted peer (which is also why the read is not O_NOFOLLOW).
    const auto directory_fits = [&](size_t start) {
        static const unsigned char kTrueType1[4] = {'1', 0, 0, 0};
        static const unsigned char kOpenType[4] = {0, 1, 0, 0};
        static const unsigned char kCff[4] = {'O', 'T', 'T', 'O'};
        static const unsigned char kApple[4] = {'t', 'r', 'u', 'e'};
        static const unsigned char kType1[4] = {'t', 'y', 'p', '1'};
        if (!tag_at(start, kTrueType1) && !tag_at(start, kOpenType) && !tag_at(start, kCff) &&
            !tag_at(start, kApple) && !tag_at(start, kType1)) {
            return false;
        }
        if (start > size || size - start < 12) {
            return false;
        }
        const uint64_t tables =
            (static_cast<uint64_t>(data[start + 4]) << 8) | data[start + 5];
        if (tables * 16u > static_cast<uint64_t>(size - start) - 12u) {
            return false;
        }
        // Every table where it says it is. Offset and length are read out of the
        // file, so the sum is done at 64 bits whatever the architecture is: at
        // 32 bits `offset + length` on two values near the top of the range
        // wraps to something small and passes the check it exists to fail.
        for (uint64_t i = 0; i < tables; ++i) {
            const size_t record = start + 12 + static_cast<size_t>(i) * 16;
            const uint64_t offset = be32(record + 8);
            const uint64_t length = be32(record + 12);
            if (offset + length > static_cast<uint64_t>(size)) {
                return false;
            }
        }
        return true;
    };

    static const unsigned char kCollection[4] = {'t', 't', 'c', 'f'};
    if (tag_at(0, kCollection)) {
        // A collection: the parser is sent to the first face's offset table, so
        // that is the one that has to be there.
        //
        // The version is asked because stb asks it: stbtt_GetFontOffsetForIndex
        // follows a `ttcf` only at header version 1.0 or 2.0
        // (imstb_truetype.h:1333) and answers -1 for anything else -- which is
        // the -1 entry 92 is about, reached through a collection instead of
        // through a file that is not a font at all. The count is read as the
        // signed value stb reads (`ttLONG`), because a negative one fails its
        // `index >= n` test and returns -1 by the same door.
        if (size < 16) {
            return false;
        }
        const uint32_t version = be32(4);
        if (version != 0x00010000u && version != 0x00020000u) {
            return false;
        }
        const uint32_t faces = be32(8);
        if (faces == 0 || faces > 0x7FFFFFFFu) {
            return false;
        }
        return directory_fits(be32(12));
    }
    return directory_fits(0);
}

// Sequence keys, translated between the bank's numbering (U+F0000 up) and the
// text's and the atlas's (kSequenceKeyFirst up, fonts.h says why). 0 for a
// key past the room, which then draws as its parts.
constexpr uint32_t kSequenceKeyRoom = kSequenceKeyLast - kSequenceKeyFirst + 1;
static_assert(kSequenceKeyRoom == 6400, "the BMP's private use area");
bool g_keys_past_room = false;

// The codepoints the text showed this frame and nobody has looked up yet, for
// fonts_look_up_noted(). More new codepoints than this in one frame are noted
// again on the next -- the text arrives whole every frame -- so the bound
// costs a frame, never a verdict.
constexpr uint32_t kMaxLookups = 256;
uint32_t g_lookups[kMaxLookups];
uint32_t g_lookup_count = 0;

uint32_t text_key(uint32_t bank_key) {
    const uint32_t offset = bank_key - kEmojiSequenceKeyFirst;
    if (bank_key < kEmojiSequenceKeyFirst || offset >= kSequenceKeyRoom) {
        g_keys_past_room = true;
        return 0;
    }
    return kSequenceKeyFirst + offset;
}

bool is_text_key(uint32_t codepoint) {
    return codepoint >= kSequenceKeyFirst && codepoint <= kSequenceKeyLast;
}

// What the bank calls this codepoint: a text key's own number on disk, and
// every other codepoint itself.
uint32_t bank_codepoint(uint32_t codepoint) {
    return is_text_key(codepoint) ? kEmojiSequenceKeyFirst + (codepoint - kSequenceKeyFirst)
                                  : codepoint;
}

// Whether this codepoint draws from the bank: the remembered verdict, or the
// one lookup that decides it. Every caller that only wants the noting ignores
// the answer; the sequence collapse below rewrites a name on it, which is why
// it is an answer and not only a side effect. False during a sandbox's wait
// for the bank, and nothing remembered then.
//
// `key` says the codepoint is a text key the collapse below produced. Nothing
// else may ask about one: a codepoint of that area anywhere else came from a
// name, and answering it would put a sequence's picture where the name only
// spelled its number.
bool bank_verdict(uint32_t codepoint, bool key = false) {
    // Below the symbols there are no emoji, and Inter's own glyphs win anyway.
    //
    // The floor is deliberate and it is not going up: the bank *does* carry the
    // fourteen codepoints under it -- the digits, `#`, `*`, `©` and `®` -- but
    // they are the bases of keycap sequences, and colouring U+0032 would draw
    // "User 2" with a keycap in it. (A keycap as a whole -- digit, box -- is a
    // sequence, and draws as one coloured glyph through its key since 0.1.9.)
    if (codepoint < 0x2000 || codepoint > 0x10FFFF) {
        return false;
    }
    // And the other half of the same decision, which was missing: U+20E3 is the
    // box a keycap sequence draws *around* its digit, it is above the floor, and
    // the bank has it -- so `1` came out of the monochrome font and the box
    // around it came out of the bank, and the user saw a grey digit inside a
    // blue tile. Half an emoji coloured is worse than none: refused here, so a
    // keycap is drawn by one font throughout.
    if (codepoint == 0x20E3) {
        return false;
    }
    if (is_text_key(codepoint) && !key) {
        return false;
    }
    long low = 0;
    long high = static_cast<long>(g_seen_count) - 1;
    while (low <= high) {
        const long middle = low + (high - low) / 2;
        const uint32_t entry = g_seen[middle] & kCodepointMask;
        if (entry == codepoint) {
            return (g_seen[middle] & kSeenInBank) != 0;  // seen before, verdict remembered either way
        }
        if (entry < codepoint) {
            low = middle + 1;
        } else {
            high = middle - 1;
        }
    }
    // Not seen yet. The verdict is a file read -- the bank's open and its
    // table the first time, a binary search of preads after that -- and this
    // runs inside the present on the Vulkan path, whose renderer said it took
    // no file work there while it did (39-139 us the first time, 6-8 us each
    // new codepoint after, measured by the 0.1.10 review; 82 bank calls on the
    // present path of vk_present_draw's arrivals scene). So nothing is read
    // here: the codepoint is queued, and fonts_look_up_noted() -- the first
    // thing ensure_fonts() does, after the present -- reads. Until then it is
    // "not from the bank", which draws it from the monochrome font for a frame.
    //
    // The bank itself is opened by the first ensure_fonts() (the first build,
    // fonts_look_up_noted), which on the Vulkan path is on the atlas worker
    // and before anything can be drawn -- so a noting there always finds it
    // asked. What can find it not asked yet is the OpenGL path's first frame,
    // which notes before its first build, inside the swap call where the
    // build happens too: it opens the bank here, as it always did.
    if (!g_emoji_bank.asked()) {
        g_emoji_bank.open();
    }
    for (uint32_t i = 0; i < g_lookup_count; ++i) {
        if (g_lookups[i] == codepoint) {
            return false;
        }
    }
    if (g_lookup_count < kMaxLookups) {
        g_lookups[g_lookup_count++] = codepoint;
    }
    return false;
}

// The lookup a queued codepoint waits for, and the verdict remembered.
void look_up(uint32_t codepoint) {
    long low = 0;
    long high = static_cast<long>(g_seen_count) - 1;
    while (low <= high) {
        const long middle = low + (high - low) / 2;
        const uint32_t entry = g_seen[middle] & kCodepointMask;
        if (entry == codepoint) {
            return;  // queued twice in one frame, or answered already
        }
        if (entry < codepoint) {
            low = middle + 1;
        } else {
            high = middle - 1;
        }
    }
    if (g_seen_count >= kMaxSeenCodepoints) {
        g_capped = true;
        return;
    }
    // The one bank lookup this codepoint will ever cost.
    bool in_bank = g_emoji_bank.contains(bank_codepoint(codepoint));
    // Unless the bank has not arrived yet, which only happens inside a Flatpak:
    // the daemon copies it in on its own tick and the game's first frame beats
    // it. Writing "no colour glyph" down now would outlive the wait -- the
    // verdict here is remembered for the life of the process -- so nothing is
    // written down at all until the bank has either opened or given up: the
    // text notes it again next frame, and it is looked up again. The open
    // behind it is rate-limited to two a second.
    if (!in_bank && g_emoji_bank.still_arriving()) {
        return;
    }
    // The atlas budget, which is a different question from the one above: past
    // it a new colour emoji stays monochrome, and it is remembered as "not in
    // the bank" so it never costs another lookup either.
    if (in_bank && g_wanted_count >= kMaxBankGlyphs) {
        in_bank = false;
        g_capped = true;
    }
    std::memmove(&g_seen[low + 1], &g_seen[low],
                 (g_seen_count - static_cast<uint32_t>(low)) * sizeof(uint32_t));
    g_seen[low] = codepoint | (in_bank ? kSeenInBank : 0);
    ++g_seen_count;
    if (in_bank) {
        ++g_wanted_count;
    }
}

// The remembered entry's flags (kSeenInBank, kSeenFolded, kSeenPlaced), or 0
// for a codepoint never seen: a search of the table, no lookup of anything
// else. kSeenPlaced is "the atlas carries a glyph for it".
uint32_t seen_flags(uint32_t codepoint) {
    long low = 0;
    long high = static_cast<long>(g_seen_count) - 1;
    while (low <= high) {
        const long middle = low + (high - low) / 2;
        const uint32_t entry = g_seen[middle] & kCodepointMask;
        if (entry == codepoint) {
            return g_seen[middle] & ~kCodepointMask;
        }
        if (entry < codepoint) {
            low = middle + 1;
        } else {
            high = middle - 1;
        }
    }
    return 0;
}

}  // namespace

void fonts_look_up_noted() {
    // The bank itself, the first time this runs: its open and its sequence
    // table's read, here -- in the first build, which on the Vulkan path is the
    // atlas worker's -- rather than inside a present. Asked whether or not any
    // text has shown an emoji yet: the table has to be there before the text
    // is read, or a sequence's parts are noted as emoji of their own.
    if (!g_emoji_bank.asked()) {
        g_emoji_bank.open();
    }
    for (uint32_t i = 0; i < g_lookup_count; ++i) {
        look_up(g_lookups[i]);
    }
    g_lookup_count = 0;
}

void fonts_note_emoji(const char* utf8_text) {
    if (!utf8_text || !utf8_text[0]) {
        return;
    }
    utf8_each(utf8_text, [](uint32_t codepoint) { bank_verdict(codepoint); });
}

void fonts_prepare_text(char* text, size_t capacity) {
    if (!text || !text[0] || capacity == 0) {
        return;
    }
    // A codepoint of the keys' area arriving in the text becomes U+FFFD, in
    // place -- both are three bytes -- before anything reads the text. It drew
    // as '?' before (no font in the atlas covers the area) and U+FFFD draws
    // the same; left alone, it would be looked up in the bank as the key of
    // that number and folded as that sequence's picture.
    //
    // Except a key whose glyph is placed, which passes: a text prepared twice
    // must come out the same (the state poll hands back the snapshot it gave
    // the previous frame when a publish outlasts its read, already collapsed),
    // and a key this function wrote cannot be told from the same number
    // spelled in a name. So a name that spells, exactly, the number of a key
    // already folded draws that key's picture where it drew '?' -- the same
    // class of collision the keys had at U+F0000, in an area names use more.
    utf8_each_span(text, [text](uint32_t codepoint, size_t begin, size_t) {
        if (is_text_key(codepoint) && (seen_flags(codepoint) & kSeenPlaced) == 0) {
            text[begin] = static_cast<char>(0xEF);
            text[begin + 1] = static_cast<char>(0xBF);
            text[begin + 2] = static_cast<char>(0xBD);
        }
    });
    // The table comes with the bank, which the first ensure_fonts() opened --
    // or, on the OpenGL path's first frame, before its first build, this does:
    // the table has to be there before the text is read, or a sequence's
    // parts are noted as emoji of their own. With no table at all (none beside
    // the bank, or no bank) the plain noting is the whole of it, exactly the
    // pre-0.1.9 cost.
    if (!g_emoji_bank.asked()) {
        g_emoji_bank.open();
    }
    if (g_emoji_bank.sequence_count() == 0) {
        fonts_note_emoji(text);
        return;
    }
    // Decoded once into fixed arrays: the widest field a snapshot has is the
    // toast's body, and a codepoint per byte is the bound. A string wider than
    // that is not a snapshot's and is left as it is.
    constexpr uint32_t kMaxCodepoints = 256;
    static_assert(kMaxCodepoints >= kNotificationBodyCapacity,
                  "every snapshot field fits the decode");
    uint32_t codepoints[kMaxCodepoints];
    size_t begins[kMaxCodepoints];
    size_t ends[kMaxCodepoints];
    uint32_t count = 0;
    bool wider = false;
    utf8_each_span(text, [&](uint32_t codepoint, size_t begin, size_t end) {
        if (count < kMaxCodepoints) {
            codepoints[count] = codepoint;
            begins[count] = begin;
            ends[count] = end;
            ++count;
        } else {
            wider = true;
        }
    });
    if (wider) {
        fonts_note_emoji(text);
        return;
    }
    // Every byte that is not part of a collapsed sequence is copied as it was,
    // malformed ones included: the walk skips them and the spans step around
    // them. A key is three bytes and a sequence is never fewer than four (its
    // shortest, a keycap without a selector), so the result is never longer
    // than the text; the check below is belt to that brace.
    char out[kMaxCodepoints];
    size_t written = 0;
    size_t copied_to = 0;
    bool changed = false;
    const size_t length = std::strlen(text);
    auto copy_raw = [&](size_t upto) -> bool {
        if (upto < copied_to || written + (upto - copied_to) >= sizeof(out)) {
            return false;
        }
        std::memcpy(out + written, text + copied_to, upto - copied_to);
        written += upto - copied_to;
        copied_to = upto;
        return true;
    };
    // Noted as it is walked, codepoint by codepoint and key by key: the text
    // may come out of here with a sequence left as its parts (below), and
    // those parts must not be noted -- each would take an atlas slot of the
    // 96 for a glyph the next frame's collapse never shows.
    for (uint32_t i = 0; i < count;) {
        uint32_t used = 0;
        const uint32_t bank_key = g_emoji_bank.sequence_key(&codepoints[i], count - i, &used);
        const uint32_t key = bank_key != 0 ? text_key(bank_key) : 0;
        // The key is asked of the bank the way any codepoint is, and remembered
        // the same way: past the atlas cap, or with the bank still arriving, it
        // is refused and the sequence stays its parts -- coloured parts, as
        // before -- rather than becoming a key no glyph answers to.
        if (key != 0 && used >= 2 && bank_verdict(key, true)) {
            // And rewritten only once the atlas HAS the key's glyph. It was
            // rewritten as soon as the bank said yes, which is before the fold
            // that puts the glyph in the atlas: the Vulkan layer notes and
            // draws in one draw() and folds after the present, so a sequence
            // nobody had shown yet drew as ImGui's fallback, a '?', for its
            // first frame (measured: the lime's key absent from the atlas
            // after the rewrite, FindGlyph answering U+003F). Noted now,
            // collapsed on the first frame after the fold; until then the
            // sequence draws as its parts, from the monochrome font.
            const uint32_t flags = seen_flags(key);
            if ((flags & kSeenPlaced) != 0) {
                if (!copy_raw(begins[i]) || written + 4 >= sizeof(out)) {
                    fonts_note_emoji(text);
                    return;
                }
                written += utf8_put(key, out + written);
                copied_to = ends[i + used - 1];
                changed = true;
            } else if ((flags & kSeenFolded) != 0) {
                // Folded and not placed -- its picture would not load or its
                // square did not pack -- so it never will be: the parts are
                // what draws it for good, and they are noted like any text.
                for (uint32_t part = i; part < i + used; ++part) {
                    bank_verdict(codepoints[part]);
                }
            }
            i += used;
        } else {
            bank_verdict(codepoints[i]);
            ++i;
        }
    }
    if (changed && copy_raw(length) && written < capacity) {
        out[written] = '\0';
        std::memcpy(text, out, written + 1);
    }
}

void fonts_note_emoji_in(Snapshot& snapshot) {
    fonts_prepare_text(snapshot.channel_name, sizeof(snapshot.channel_name));
    for (uint32_t i = 0; i < snapshot.user_count && i < kMaxUsers; ++i) {
        fonts_prepare_text(snapshot.users[i].name, sizeof(snapshot.users[i].name));
    }
    fonts_prepare_text(snapshot.notification.title, sizeof(snapshot.notification.title));
    fonts_prepare_text(snapshot.notification.body, sizeof(snapshot.notification.body));
}

uint32_t fonts_build_count() { return g_build_count; }

uint32_t fonts_take_folded(AtlasRegion* out, uint32_t capacity) {
    const uint32_t count = g_folded_count < capacity ? g_folded_count : capacity;
    for (uint32_t i = 0; i < count && out; ++i) {
        out[i] = g_folded[i];
    }
    g_folded_count = 0;
    return count;
}

const char* fonts_font_status() { return g_font_reason; }

const char* fonts_emoji_status() {
    // The bank's own refusal first: it is the one that means "none at all".
    if (const char* reason = g_emoji_bank.reason()) {
        return reason;
    }
    if (g_capped) {
        return "the colour emoji table is full: further emoji stay monochrome";
    }
    // Set only once the bank has opened: a bank without its sequence table
    // draws every codepoint in colour and every sequence as its parts.
    if (const char* reason = g_emoji_bank.sequences_reason()) {
        return reason;
    }
    if (g_keys_past_room) {
        return "the emoji sequence table has more keys than the private use area holds: "
               "those sequences draw as their parts";
    }
    return nullptr;
}

const Fonts& fonts() { return g_fonts; }

ImFontAtlas* fonts_atlas() {
    // Leaked on purpose, and the `new` is the whole point.
    //
    // A function-local static object would also have the compiler register
    // ~ImFontAtlas with __cxa_atexit, and that destructor deletes every ImFont
    // and frees the 16 MB + 64 MB of pixels -- at exit(), from whichever thread
    // called it, while a render thread may still be inside draw() holding the
    // lock and dereferencing g.Font. The atexit list runs LIFO, so it would also
    // run BEFORE the ELF destructor that closes the journal, leaving a `.running`
    // behind: the overlay reporting, in the window's Debug section, a crash it
    // caused itself. IM_ASSERT is compiled out of both injected targets, so
    // there would not even be an abort to read.
    //
    // This is the decision gl/src/vocem_gl.cpp makes for overlay() in the same
    // words and for the same reason (entry 132), and a function-local static
    // here quietly took it back for the one object that matters most. A pointer
    // still costs a guard variable and nothing else: no destructor is registered
    // because there is none to run.
    //
    // And said, before it is handed to anybody: fonts_atlas_made() is how a
    // teardown on another thread learns that there is something to release
    // without making it.
    static ImFontAtlas* atlas = [] {
        ImFontAtlas* made = new ImFontAtlas;
        g_atlas_made.store(true, std::memory_order_release);
        return made;
    }();
    return atlas;
}

bool fonts_atlas_made() { return g_atlas_made.load(std::memory_order_acquire); }

void fonts_release() {
    ImFontAtlas* atlas = fonts_atlas();
    // ImGui locks the atlas for the length of a frame and unlocks it in
    // EndFrame -- and its Shutdown unlocks it too, but only for the atlas the
    // context owns, which this one is not. A context torn down between NewFrame
    // and EndFrame would leave it locked forever, so the lock is dropped here
    // and in build_atlas() rather than trusted.
    atlas->Locked = false;
    atlas->Clear();
    g_fonts.body = nullptr;
    g_fonts.strong = nullptr;
    g_fonts.pixel_size = 0.0f;
    // What is in the atlas, not what the session has seen: the emoji the text
    // asked for are still wanted, and the next build carries them again. Clear()
    // took the reserved rectangles with everything else, so nothing is folded
    // any more either -- said here as well as in build_atlas(), because a module
    // whose state describes an atlas that no longer exists is how a pointer into
    // a dead atlas gets used (entry 37).
    g_built_count = 0;
    g_folded_count = 0;
    g_emoji_reserved = false;
    g_emoji_slots = 0;
    for (uint32_t i = 0; i < kMaxRects; ++i) {
        g_emoji_rects[i] = -1;
    }
    for (uint32_t i = 0; i < g_seen_count; ++i) {
        g_seen[i] &= ~(kSeenFolded | kSeenPlaced);
    }
    g_asked_body[0] = '\0';
    g_asked_strong[0] = '\0';
    g_body_path[0] = '\0';
    g_strong_path[0] = '\0';
    g_font_reason = nullptr;
}

float font_pixel_size(uint32_t height, float user_scale, float reference) {
    // Whole pixels. The size is what every distance in the panel is a multiple of,
    // and ImGui truncates the content extent it fits a window to: with a fractional
    // line height the accumulated fraction came off the bottom padding and the last
    // avatar in the list was clipped by the box's own edge. It is also the size the
    // glyphs are rasterised at, and a whole number is the crisper of the two.
    const float proportional = std::round(
        reference * (static_cast<float>(height) / kReferenceHeight) * user_scale);
    // Below about 11 pixels an interface font stops being readable at all, and
    // above 64 the atlas grows faster than the value of the extra detail.
    if (proportional < 11.0f) {
        return 11.0f;
    }
    if (proportional > 64.0f) {
        return 64.0f;
    }
    return proportional;
}

float ui_scale() {
    const float reference = g_fonts.reference > 0.0f ? g_fonts.reference : kReferenceSize;
    return g_fonts.pixel_size > 0.0f ? g_fonts.pixel_size / reference : 1.0f;
}

namespace {

// The one lookup entry a folded glyph needs, written in place: what
// BuildLookupTable() would set for it, and nothing else. BuildLookupTable itself
// clears and re-grows both index arrays to the highest codepoint in the font
// and walks every glyph, twice per fold -- and with a sequence key at its
// on-disk number (U+F0000 up, entry 142) in the font that was 984,119 entries
// a weight: measured at 1.6 to 4.2 ms a fold against 0.24 to 0.50 with none,
// three runs each, on the path the fold runs on (entry 209). The keys are
// numbered inside the index the atlas already has now (kSequenceKeyFirst,
// fonts.h), so this grows nothing for them; the growth below is for a
// codepoint above the index, with the fallback advance BuildLookupTable gives
// an empty entry.
void index_folded_glyph(ImFont* font, uint32_t codepoint) {
    const int index = font->Glyphs.Size - 1;
    const int at = static_cast<int>(codepoint);
    if (at >= font->IndexLookup.Size) {
        const int old_size = font->IndexAdvanceX.Size;
        font->GrowIndex(at + 1);
        for (int i = old_size; i < font->IndexAdvanceX.Size; ++i) {
            font->IndexAdvanceX[i] = font->FallbackAdvanceX;
        }
    }
    font->IndexAdvanceX[at] = font->Glyphs[index].AdvanceX;
    font->IndexLookup[at] = static_cast<ImU16>(index);
    const int page = at / 8192;
    font->Used8kPagesMap[page >> 3] |= static_cast<ImU8>(1 << (page & 7));
    font->DirtyLookupTables = false;
}

// Puts every wanted bank emoji that is not in the atlas yet INTO the atlas,
// without rebuilding it: the pixels go into a rectangle Build() already packed,
// and the glyph is registered by hand with exactly the four lines
// ImFontAtlasBuildFinish runs for a custom-rect glyph (imgui_draw.cpp, "Register
// custom rectangle glyphs"). Returns whether anything was folded, which is the
// caller's signal that the font texture on the GPU no longer matches the atlas.
//
// This is the whole point of reserving the rects. Adding one emoji used to mean
// atlas->Clear() and atlas->Build(): 14,954 glyphs in two weights rasterised
// again to make room for one 32x32 square -- measured at 125 to 145 ms, six
// times over, on the machine DESIGN's numbers come from. The same emoji folded
// in here is 0.3 to 0.9 ms, three runs (entry 191). A person joining a channel
// with an emoji in their name, or a message arriving with one in it, is exactly
// when that used to be spent, which is why the owner felt it as a freeze.
//
// Still not free: a bank read, a resample, two memcpys and a lookup table per
// weight. It runs where the rebuild ran -- after the present on the Vulkan path,
// inside the swap call on the OpenGL one.
bool fold_wanted_emoji(ImFontAtlas* atlas) {
    if (!g_emoji_reserved || g_built_count >= g_wanted_count) {
        return false;
    }
    // The RGBA the fold writes into. Built by the first caller to ask; after
    // that this is the cached pointer and costs nothing (measured at 0.0 ms).
    unsigned char* pixels = nullptr;
    int atlas_width = 0;
    int atlas_height = 0;
    atlas->GetTexDataAsRGBA32(&pixels, &atlas_width, &atlas_height);
    if (!pixels) {
        return false;
    }

    unsigned char record[kEmojiBankRgbaBytes];
    unsigned char scaled[kEmojiBankRgbaBytes];
    bool folded_any = false;
    bool lookup_dirty = false;
    for (uint32_t i = 0; i < g_seen_count && g_emoji_slots < kMaxBankGlyphs; ++i) {
        if ((g_seen[i] & kSeenInBank) == 0 || (g_seen[i] & kSeenFolded) != 0) {
            continue;
        }
        const uint32_t codepoint = g_seen[i] & kCodepointMask;
        // Whatever happens below, this codepoint is not asked about again: a
        // bank read that fails now fails the same way next frame, and a rect
        // that did not pack will not pack later either. Marked before the work
        // so no path out of here leaves it to be retried every frame -- that is
        // the shape the font-path bug of entry 129's neighbourhood had, 61 ms a
        // frame forever because a failure did not settle.
        g_seen[i] |= kSeenFolded;
        ++g_built_count;

        if (!g_emoji_bank.load(bank_codepoint(codepoint), record)) {
            continue;
        }
        const uint32_t slot = g_emoji_slots;
        ImFont* const weights[kAtlasWeights] = {g_fonts.body, g_fonts.strong};
        bool placed = false;
        for (uint32_t weight = 0; weight < kAtlasWeights; ++weight) {
            const int index = g_emoji_rects[slot * kAtlasWeights + weight];
            if (index < 0) {
                continue;
            }
            const ImFontAtlasCustomRect* rect = atlas->GetCustomRectByIndex(index);
            if (!rect->IsPacked()) {
                continue;
            }
            emoji_bank_resample(record, scaled, static_cast<uint32_t>(rect->Width));
            for (int row = 0; row < rect->Height; ++row) {
                std::memcpy(pixels + ((rect->Y + row) * atlas_width + rect->X) * 4,
                            scaled + row * rect->Width * 4,
                            static_cast<size_t>(rect->Width) * 4);
            }
            ImVec2 uv0;
            ImVec2 uv1;
            atlas->CalcCustomRectUV(rect, &uv0, &uv1);
            weights[weight]->AddGlyph(nullptr, static_cast<ImWchar>(codepoint), 0.0f,
                                      g_emoji_offset_y, static_cast<float>(rect->Width),
                                      g_emoji_offset_y + static_cast<float>(rect->Height),
                                      uv0.x, uv0.y, uv1.x, uv1.y,
                                      static_cast<float>(rect->Width + 1));
            weights[weight]->Glyphs.back().Colored = 1;
            index_folded_glyph(weights[weight], codepoint);
            if (g_folded_count < kMaxRects) {
                g_folded[g_folded_count++] = AtlasRegion{rect->X, rect->Y, rect->Width, rect->Height};
            }
            lookup_dirty = true;
            placed = true;
        }
        if (placed) {
            g_seen[i] |= kSeenPlaced;
            ++g_emoji_slots;
            folded_any = true;
        }
    }

    // Once, after all of them: Glyphs may have reallocated under AddGlyph, and
    // FallbackGlyph is a pointer into it -- entry 37's hazard in a new place.
    // The index entries were written glyph by glyph above; only the pointer is
    // left to put back on a live glyph.
    if (lookup_dirty) {
        for (ImFont* font : {g_fonts.body, g_fonts.strong}) {
            if (!font) {
                continue;
            }
            font->FallbackGlyph = font->FindGlyphNoFallback(font->FallbackChar);
            if (!font->FallbackGlyph) {
                font->BuildLookupTable();  // what ImGui itself does to find one
            }
        }
    }
    return folded_any;
}

// One whole build of the atlas, from the two paths already recorded in
// g_body_path / g_strong_path, answering whether the rasteriser accepted what it
// was given.
//
// A function rather than a stretch of ensure_fonts() because it has to be
// runnable twice: a chosen face that gets past looks_like_a_font() and still
// cannot be rasterised leaves ImGui with an atlas of no pixels at all -- measured
// at 0x0, with every font pointer unloaded, against a variable OpenType
// (Cantarell-VF.otf: CFF2, which stb_truetype does not implement) -- and an
// overlay that draws no text while reporting nothing is the silence entry 38 is
// about. The second run is the carried Inter alone, which is the one build this
// project knows always works.
bool build_atlas(ImFontAtlas* atlas, float pixel_size) {
    // See fonts_release(): nobody else unlocks an atlas this module owns.
    atlas->Locked = false;
    atlas->Clear();

    ImFontConfig config;
    config.FontDataOwnedByAtlas = false;  // the data is static, not heap
    // Inter's outlines are drawn for interfaces; the light hinting ImGui applies by
    // default is right for it. Oversampling stays at ImGui's default of 2 in the
    // horizontal direction, which is what makes small text look clean.

    // A merged glyph belongs to the font it was merged into, so each weight gets
    // its own copy of the emoji and the punctuation: the channel name is drawn in
    // the heavier one, and it is exactly where an emoji turns up.
    const float emoji_size = pixel_size < kEmojiCeiling ? pixel_size : kEmojiCeiling;
    // The user's own face first, with Inter merged straight underneath it as the
    // fallback: ImGui's merge keeps the glyph that is already there, so the
    // chosen font wins everywhere it has an opinion and Inter fills in the
    // scripts and symbols it does not carry. Without that fallback, picking a
    // Latin-only display face would turn every Cyrillic name into question
    // marks -- a font choice is not a decision to stop drawing people's names.
    auto add_weight = [&](const unsigned char* data, unsigned int size, const char* path) {
        ImFont* font = nullptr;
        if (path[0]) {
            size_t bytes = 0;
            if (void* file = read_font_file(path, &bytes)) {
                if (!looks_like_a_font(static_cast<const unsigned char*>(file), bytes)) {
                    // Ours to free: nothing has taken it yet, and handing it on
                    // is what crashes.
                    IM_FREE(file);
                    g_font_reason = "the chosen font is not a font file";
                } else {
                    ImFontConfig chosen = config;
                    // The atlas owns this copy and frees it -- at its next
                    // Clear(), or with the context if the game destroys it. The
                    // carried fonts are static and stay owned by nobody.
                    // AddFontFromMemoryTTF cannot answer null (it returns
                    // AddFont's DstFont, imgui_draw.cpp:2612), so there is no
                    // failure to test for here: whether the bytes rasterise is
                    // Build()'s answer, taken at the bottom of this function.
                    chosen.FontDataOwnedByAtlas = true;
                    font = atlas->AddFontFromMemoryTTF(file, static_cast<int>(bytes), pixel_size,
                                                       &chosen, letter_ranges());
                }
            }
        }
        if (font) {
            ImFontConfig fallback = config;
            fallback.MergeMode = true;
            atlas->AddFontFromMemoryCompressedTTF(data, static_cast<int>(size), pixel_size,
                                                  &fallback, letter_ranges());
        } else {
            font = atlas->AddFontFromMemoryCompressedTTF(data, static_cast<int>(size), pixel_size,
                                                         &config, letter_ranges());
        }

        ImFontConfig merge = config;
        merge.MergeMode = true;
        // The symbol fonts before the punctuation and the emoji, at their own
        // ceiling (symbol_ranges says why there is one): Math first -- it has
        // the best versions of the shared arrows -- then the two Symbols.
        const float symbol_size = pixel_size < kSymbolCeiling ? pixel_size : kSymbolCeiling;
        atlas->AddFontFromMemoryCompressedTTF(
            NotoMath_compressed_data, static_cast<int>(NotoMath_compressed_size),
            symbol_size, &merge, symbol_ranges());
        atlas->AddFontFromMemoryCompressedTTF(
            NotoSymbols2_compressed_data, static_cast<int>(NotoSymbols2_compressed_size),
            symbol_size, &merge, symbol_ranges());
        atlas->AddFontFromMemoryCompressedTTF(
            NotoSymbols_compressed_data, static_cast<int>(NotoSymbols_compressed_size),
            symbol_size, &merge, symbol_ranges());
        atlas->AddFontFromMemoryCompressedTTF(
            NotoPunctuation_compressed_data,
            static_cast<int>(NotoPunctuation_compressed_size), pixel_size, &merge,
            punctuation_ranges());
        atlas->AddFontFromMemoryCompressedTTF(
            NotoEmoji_compressed_data, static_cast<int>(NotoEmoji_compressed_size),
            emoji_size, &merge, emoji_ranges());
        return font;
    };

    g_fonts.body = add_weight(InterRegular_compressed_data, InterRegular_compressed_size,
                              g_body_path);
    g_fonts.strong = add_weight(InterSemiBold_compressed_data, InterSemiBold_compressed_size,
                                g_strong_path);

    // A failure here would leave the atlas empty and ImGui would assert on the
    // first frame, so fall back to the built-in bitmap rather than draw nothing.
    if (!g_fonts.body) {
        atlas->AddFontDefault();
        g_fonts.body = atlas->Fonts.empty() ? nullptr : atlas->Fonts[0];
        g_fonts.strong = g_fonts.body;
    }
    if (!g_fonts.strong) {
        g_fonts.strong = g_fonts.body;
    }

    // The space the colour emoji will occupy, reserved now and bound to a
    // codepoint later. Each weight gets its own rect (a merged glyph belongs to
    // the font it was merged into -- the same lesson the monochrome emoji
    // taught), and EVERY rect the session's cap allows is reserved here, seen or
    // not: 96 emoji in two weights at 32 px is 1.2% of a 4096x4096 atlas, and it
    // is what buys fold_wanted_emoji() a place to put a new emoji without
    // rasterising the other fourteen thousand glyphs again. The monochrome font
    // stays merged underneath: a codepoint past the seen-cap, or a session with
    // no bank on disk, draws exactly as it did before this existed.
    //
    // Reserved as REGULAR rects, with no font and no glyph id, so Build() packs
    // them and registers nothing; the binding is fold_wanted_emoji()'s, and it
    // does by hand exactly what ImFontAtlasBuildFinish does for a glyph rect.
    const int emoji_px = static_cast<int>(emoji_size);
    g_emoji_offset_y = std::round((pixel_size - emoji_size) * 0.5f);
    for (uint32_t i = 0; i < kMaxRects; ++i) {
        g_emoji_rects[i] = -1;
    }
    g_emoji_slots = 0;
    g_emoji_reserved = g_fonts.body && g_fonts.strong && g_fonts.body != g_fonts.strong;
    if (g_emoji_reserved) {
        for (uint32_t i = 0; i < kMaxRects; ++i) {
            g_emoji_rects[i] = atlas->AddCustomRectRegular(emoji_px, emoji_px);
        }
    }

    // Nothing in the new atlas carries anybody's pixels yet, whatever the old
    // one carried: the flags belong to the atlas, not to the session's memory of
    // what it has seen.
    for (uint32_t i = 0; i < g_seen_count; ++i) {
        g_seen[i] &= ~(kSeenFolded | kSeenPlaced);
    }
    g_built_count = 0;
    g_folded_count = 0;

    // The rasteriser's own answer, which nothing used to ask for. False means it
    // could not parse one of the sources: the atlas has no pixels, every font in
    // it is unloaded, and the caller has to build something else.
    const bool built = atlas->Build();
    ++g_build_count;

    if (built) {
        fold_wanted_emoji(atlas);
        // Folded into a texture that does not exist yet: the caller uploads the
        // whole atlas after a build, so these are already in it.
        g_folded_count = 0;
        // The RGBA32 copy is the atlas from here on: both backends upload it,
        // and a fold writes its colour glyph into it. The alpha8 image the
        // rasteriser drew is read once, by the widening (in a fold above or the call below), and was then
        // kept for the life of the atlas -- 16 MB at a 4K display's text size,
        // in every process that draws, which is a fifth of what this module
        // holds. Measured on gl_daemon_gone: 83,452 kB handed back at a quit
        // before this and 67,064 after, three runs each to the kB (entry 207). ImGui rebuilds the whole atlas if
        // anything asks it for alpha8 afterwards (GetTexDataAsAlpha8 calls
        // Build() on a null image); nothing in the injected code does, and the
        // widening only asks for it while the RGBA copy does not exist, which
        // after a Clear() is a rebuild anyway.
        unsigned char* rgba = nullptr;
        atlas->GetTexDataAsRGBA32(&rgba, nullptr, nullptr);
        if (rgba && atlas->TexPixelsAlpha8) {
            IM_FREE(atlas->TexPixelsAlpha8);
            atlas->TexPixelsAlpha8 = nullptr;
        }
    }

    return built;
}

}  // namespace

bool ensure_fonts(float pixel_size, float reference, const char* body_path,
                  const char* strong_path) {
    // What the frames' text noted and nobody has looked up: this is the
    // post-present phase, and the lookups are file reads.
    fonts_look_up_noted();

    // The reference is not a size the atlas is built at -- it is what the layout
    // divides by -- so it costs nothing to follow immediately.
    g_fonts.reference = reference > 0.0f ? reference : kReferenceSize;

    // Empty and null are the same answer -- the carried Inter -- and a family
    // with no bold face on this machine draws both weights from the one file it
    // does have, which is what the window writes when fontconfig hands it the
    // same path twice.
    const char* wanted_body = body_path ? body_path : "";
    const char* wanted_strong = strong_path && strong_path[0] ? strong_path : wanted_body;
    if (std::strlen(wanted_body) >= kMaxFontPath || std::strlen(wanted_strong) >= kMaxFontPath) {
        wanted_body = "";
        wanted_strong = "";
        g_font_reason = "the chosen font's path is longer than a path should be";
    }
    // Against what was asked for, not against what was used: a refused face is
    // still the setting in front of us, and asking again cannot make it load.
    // The refusal stands until the settings name a different file, exactly as it
    // does for a file that is not a font at all.
    const bool same_font = std::strcmp(g_asked_body, wanted_body) == 0 &&
                           std::strcmp(g_asked_strong, wanted_strong) == 0;

    ImFontAtlas* atlas = ImGui::GetIO().Fonts;

    // Half a pixel of difference is not worth throwing an atlas away for -- and
    // without a dead band, a size derived from a continuous slider would rebuild
    // on every frame the user is dragging it.
    //
    // It is a promise that the ImFont pointers below still point at live glyphs,
    // so it is made about the atlas this module owns and about no other. Both
    // injected paths destroy their ImGui context and create another in the same
    // process -- the GL overlay when the user switches it off and back on or the
    // game replaces its context, the Vulkan layer when a game replaces its
    // device -- and they create the new one with fonts_atlas(), which therefore
    // survives. A context created with an atlas of its own gets that atlas
    // filled and nothing promised: it can die under this module at any time, and
    // the two ways of noticing from outside both fail (fonts.h says how).
    if (atlas == fonts_atlas() && g_fonts.pixel_size > 0.0f &&
        pixel_size > g_fonts.pixel_size - 0.5f && pixel_size < g_fonts.pixel_size + 0.5f &&
        same_font) {
        // The size and the typeface are the ones in the atlas, so the only thing
        // that can be missing is a colour emoji nobody had seen when it was
        // built -- and that is the one change this module can make without
        // building anything. It used to fall through to the full rebuild below,
        // which is the 125-145 ms a new person's name or an arriving message
        // spent in somebody's game (fold_wanted_emoji says the rest).
        if (g_built_count == g_wanted_count) {
            return false;
        }
        const bool folded = fold_wanted_emoji(atlas);
        // Settled either way. A fold that could not happen -- no reserved rects,
        // because the two weights are the same font -- must not leave the counts
        // apart, or every frame from here on walks back into the fold for
        // nothing.
        g_built_count = g_wanted_count;
        return folded;
    }

    // A new build answers for itself: a refusal from the last one would
    // otherwise be reported forever, including after the user picked a font that
    // does load.
    g_font_reason = nullptr;
    std::snprintf(g_asked_body, sizeof(g_asked_body), "%s", wanted_body);
    std::snprintf(g_asked_strong, sizeof(g_asked_strong), "%s", wanted_strong);
    std::snprintf(g_body_path, sizeof(g_body_path), "%s", wanted_body);
    std::snprintf(g_strong_path, sizeof(g_strong_path), "%s", wanted_strong);

    // A chosen face the rasteriser cannot parse is refused the way an unreadable
    // file is: the paths are forgotten, the reason is said, and the atlas is
    // built again from the carried Inter alone. Without the second build the
    // game keeps an atlas of no pixels -- no names, no channel, no message, and
    // nothing in the log to say why.
    if (!build_atlas(atlas, pixel_size) && (g_body_path[0] || g_strong_path[0])) {
        g_font_reason = "the chosen font could not be rasterised";
        g_body_path[0] = '\0';
        g_strong_path[0] = '\0';
        build_atlas(atlas, pixel_size);
    }

    g_built_count = g_wanted_count;
    g_fonts.pixel_size = pixel_size;
    return true;
}

}  // namespace vocem
